In [ ]:
import numpy as np
a = np.arange(0,16,1.1)
a

In [ ]:
import numpy as np
a = np.linspace(0,10, num=25)
a

In [ ]:
import numpy as np
col = int(input("Enter colmun size "))
row = int(input("Enter row size "))
matrix = np.ndarray(shape=(row,col), dtype=np.float32)
matrix

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
def mandelbrot(h, w, maxit=50, r=4):
    """Returns an image of the Mandelbrot fractal of size (h,w)."""
    x = np.linspace(-2.5, 1.5, 4*h+1)
    y = np.linspace(-1.5, 1.5, 3*w+1)
    A, B = np.meshgrid(x, y)
    C = A + B*1j
    z = np.zeros_like(C)
    divtime = maxit + np.zeros(z.shape, dtype=int)

    for i in range(maxit):
        z = z**2 + C
        diverge = abs(z) > r
        div_now = diverge & (divtime == maxit) # who is diverging now
        divtime[div_now] = i # note when
        z[diverge] = r # avoid diverging too much

    return divtime
plt.imshow(mandelbrot(200, 200))

In [ ]:
import numpy as np
a = np.arange(24).reshape(3,2,4)
a

In [ ]:
import numpy as np
numb = np.arange(5)
numb

In [ ]:
import numpy as np
a = np.arange(32).reshape(4,2,4)
a

In [ ]:
import numpy as np
food = np.array(['pakora', 'samosa', 'raita'])
food

In [ ]:
food[2]

In [ ]:
type(food)

In [ ]:
type(food[0])

In [ ]:
len(food)

In [ ]:
len(food[0])

In [ ]:
len(food[2])

In [ ]:
import numpy as np
number = np.arange(12)
number

In [ ]:
import numpy as np
np.ones(5, dtype=int)

In [ ]:
a=np.zeros(5, dtype=float)
print(a,)
print(type(a))
type(a[1])

In [ ]:
b=np.arange(5,10)
b

In [ ]:

np.empty(4)

In [ ]:
tb = np.arange(0,51,5)
tb

In [ ]:
lin = np.linspace(0,50, num=11)
lin

In [ ]:
import numpy as np
tb = np.arange(0,56,5)
tbr=tb.reshape(2,2,3)
print(tb)
print(tbr)
print(len(tb))
lin = np.linspace(0,50, num=21)
print(lin)
print(len(lin))
c = np.concatenate((tb, lin))
print(c)
c.sort()
print(c)
print(type(c))
print(type(c[5]))
print(len(c))

In [ ]:
import numpy as np
tb = np.arange(0,56,5)
tbr=tb.reshape(2,6)
print(tb)
print(tbr)
print(len(tb))
lin = np.linspace(60,71, num=12)
print(lin)
print(len(lin))
linr = lin.reshape(2,6)
print(linr)
print(len(linr))
c = np.concatenate((tbr, linr), axis=0)
print(c)

In [ ]:
import numpy as np
tb = np.arange(0,56,5)
tbr=tb.reshape(2,6)
print(tb)
print(tbr)
print(len(tb))
lin = np.linspace(60,71, num=12)
print(lin)
print(len(lin))
linr = lin.reshape(2,6)
print(linr)
print(len(linr))
c = np.concatenate((tbr, linr), axis=1)
print(c)

In [ ]:
import numpy as np
tb = np.arange(0,56,5)
tbr=tb.reshape(2,2,3)
print(tb)
print(tbr)
print(len(tb))
lin = np.linspace(100,111, num=12)
print(lin)
print(len(lin))
linr = lin.reshape(2,2,3)
print(linr)
print(len(linr))
c = np.concatenate((tbr, linr), axis=0)
print(c)

In [ ]:
import numpy as np
tb = np.arange(0,56,5)
tbr=tb.reshape(2,2,3)
print(tb)
print(tbr)
print(len(tb))
lin = np.linspace(100,111, num=12)
print(lin)
print(len(lin))
linr = lin.reshape(2,2,3)
print(linr)
print(len(linr))
c = np.concatenate((tbr, linr), axis=1)
print(c)

In [ ]:
import numpy as np
tb = np.arange(0,56,5)
tbr=tb.reshape(2,2,3)
print(tb)
print(tbr)
print(len(tb))
lin = np.linspace(100,111, num=12)
print(lin)
print(len(lin))
linr = lin.reshape(2,2,3)
print(linr)
print(len(linr))
c = np.concatenate((tbr, linr), axis=2)
print(c)
c.ndim

In [ ]:
import numpy as np
a = np.array([[1,2,3,4,5],[11,22,33,44,55]])
print(a)

In [4]:
import numpy as np
a = np.array([[1,2,3,4,5,6],[11,22,33,44,55,66]])
print(a)
print(np.shape(a))
print(a.ndim)
print(type(a))
b = a.reshape(2,3,2)
print(b)
print(b.ndim)
print(a.size, b.size)
print(b.shape)


[[ 1  2  3  4  5  6]
 [11 22 33 44 55 66]]
(2, 6)
2
<class 'numpy.ndarray'>
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[11 22]
  [33 44]
  [55 66]]]
3
12 12
(2, 3, 2)


In [9]:
import numpy as np
d = np.arange(9)
print(d)
print(d.size, d.ndim)

[0 1 2 3 4 5 6 7 8]
9 1


In [52]:
import numpy as np
d = np.arange(9)
print(d)
print(d.size, d.ndim)
e = d[np.newaxis, 0:9:1]
print(e)
print(e.size, e.ndim, e.shape)
f = d[0:9:1, np.newaxis]
print(f)
print(f.size, f.ndim, f.shape)
x = e*f
print(x)
print(x.size, x.ndim, x.shape)
x.sum(axis=0)
x.std()


[0 1 2 3 4 5 6 7 8]
9 1
[[0 1 2 3 4 5 6 7 8]]
9 2 (1, 9)
[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]
9 2 (9, 1)
[[ 0  0  0  0  0  0  0  0  0]
 [ 0  1  2  3  4  5  6  7  8]
 [ 0  2  4  6  8 10 12 14 16]
 [ 0  3  6  9 12 15 18 21 24]
 [ 0  4  8 12 16 20 24 28 32]
 [ 0  5 10 15 20 25 30 35 40]
 [ 0  6 12 18 24 30 36 42 48]
 [ 0  7 14 21 28 35 42 49 56]
 [ 0  8 16 24 32 40 48 56 64]]
81 2 (9, 9)


16.055459438389725

In [42]:
import numpy as np
d = np.arange(9)
print(d)
print(d.size, d.ndim)
d[-4:12]

[0 1 2 3 4 5 6 7 8]
9 1


array([5, 6, 7, 8])